import type {EditorConfig} from './types';

export const defaultConfig: EditorConfig = {
  schemaVersion: 1,
  title: '可编辑包装预览',
  width: 1920,
  height: 1080,
  fps: 30,
  durationInFrames: 480,
  backgroundColor: '#111416',
  assets: [
    {
      id: 'talking-head',
      label: '人物口播',
      kind: 'color',
      color: '#2d3437',
    },
    {
      id: 'screen-recording-a',
      label: '录屏 A',
      kind: 'color',
      color: '#1f5360',
    },
    {
      id: 'screen-recording-b',
      label: '录屏 B',
      kind: 'color',
      color: '#5a3b25',
    },
    {
      id: 'github-card',
      label: 'GitHub 截图',
      kind: 'color',
      color: '#263e32',
    },
    {
      id: 'concept-grid',
      label: '科技网格',
      kind: 'color',
      color: '#252735',
    },
  ],
  scenes: [
    {
      id: 'intro',
      title: '先看清楚，再决定怎么剪',
      assetId: 'talking-head',
      layout: 'fullscreen',
      effect: 'glow-wake-sleep-panel',
      effectIntensity: 0.62,
      pipScale: 0.24,
      from: 0,
      durationInFrames: 150,
      visible: true,
    },
    {
      id: 'evidence',
      title: '素材槽位可以直接替换',
      assetId: 'screen-recording-a',
      layout: 'pip-br',
      effect: 'line-carry-transition',
      effectIntensity: 0.7,
      pipScale: 0.24,
      from: 150,
      durationInFrames: 180,
      visible: true,
    },
    {
      id: 'result',
      title: '不满意就换参数，不必重写组件',
      assetId: 'github-card',
      layout: 'right-rail',
      effect: 'flash-cut',
      effectIntensity: 0.5,
      pipScale: 0.25,
      from: 330,
      durationInFrames: 150,
      visible: true,
    },
  ],
};
